"""Add changes

Revision ID: 1bb5c73897e9
Revises: ca647aa193bf
Create Date: 2023-08-24 06:23:52.097728

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1bb5c73897e9'
down_revision = 'ca647aa193bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeeentry', sa.Column('service_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employeeentry', 'service_id')
    # ### end Alembic commands ###
