"""drop field to employee

Revision ID: 35045f1bbe09
Revises: e421799edb60
Create Date: 2023-08-11 10:17:52.604892

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '35045f1bbe09'
down_revision = 'e421799edb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'individualRate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('individualRate', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
