"""Add changes

Revision ID: 586030aa846b
Revises: 6742af6895b3
Create Date: 2022-09-23 14:02:32.256815

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '586030aa846b'
down_revision = '6742af6895b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoiceEmailSent', sa.Boolean(), nullable=True))
    op.add_column('invoice', sa.Column('invoiceEmailSentAt', sa.DateTime(), nullable=True))
    op.add_column('invoice', sa.Column('invoiceEmailSentBy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'invoiceEmailSentBy')
    op.drop_column('invoice', 'invoiceEmailSentAt')
    op.drop_column('invoice', 'invoiceEmailSent')
    # ### end Alembic commands ###
