"""Add changes

Revision ID: b3f3fc63bddd
Revises: 1bb5c73897e9
Create Date: 2023-08-24 07:10:38.777708

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b3f3fc63bddd'
down_revision = '1bb5c73897e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'rate')
    # ### end Alembic commands ###
