"""added changes on branch employee contract tables

Revision ID: c4cbd9330b4a
Revises: 
Create Date: 2024-02-22 13:06:16.375780

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4cbd9330b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('services', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_branch_name'), 'branch', ['name'], unique=False)
    op.add_column('contract', sa.Column('services', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('employee', sa.Column('services', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('employee', 'individualRate')
    op.add_column('employeeentry', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_supportingdocument_name'), 'supportingdocument', ['name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_firstName'), 'user', ['firstName'], unique=False)
    op.create_index(op.f('ix_user_lastName'), 'user', ['lastName'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_userName'), 'user', ['userName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userName'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_lastName'), table_name='user')
    op.drop_index(op.f('ix_user_firstName'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_supportingdocument_name'), table_name='supportingdocument')
    op.drop_column('employeeentry', 'service_id')
    op.add_column('employee', sa.Column('individualRate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employee', 'services')
    op.drop_column('contract', 'services')
    op.drop_index(op.f('ix_branch_name'), table_name='branch')
    op.drop_column('branch', 'services')
    # ### end Alembic commands ###
