"""Add changes

Revision ID: ca647aa193bf
Revises: 35045f1bbe09
Create Date: 2023-08-24 05:47:26.331041

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca647aa193bf'
down_revision = '35045f1bbe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
